[package]
name = "configurable-internal"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.102"
quote = "1.0.41"
syn = { version = "2.0", features = ["full", "extra-traits", "visit-mut"] }
lazy_static = "1.5.0"
